# The URL the site will be built for
base_url = "https://sitehere.com"
title = "lookr"
description = "A really cool blog"
author="moddr"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Generates info for RSS readers
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "visual-studio-dark"

[extra]
# Put all your custom variables here'
author = "moddr"
github_account = "m0ddr"
bluesky_account = "moddr.xyz"

[extra.content]
index_title = "Hey there!"
index_content = "<span class='dark:text-blue-400 text-blue-600'>Lorem ipsum odor amet</span>, consectetuer adipiscing elit. Sapien lacinia et sit imperdiet habitasse maecenas venenatis suscipit. Habitasse dapibus tellus platea ad tellus id. Erat sodales aliquam nulla vulputate habitasse senectus conubia. Class habitasse semper dis ad integer."